version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    volumes:
      - ./html:/opt/nginx/html
      - ./nginx.conf:/opt/nginx/nginx.conf
    #  - ./certs:/opt/certs